/*
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SpeechToTextRequestContract struct {
	Model string `json:"model"`
	Dtype string `json:"dtype"`
	Input *OneOfSpeechToTextRequestContractInput `json:"input"`
	ReturnTimestamps string `json:"return_timestamps,omitempty"`
	Stream bool `json:"stream,omitempty"`
	ChunkLengthS int32 `json:"chunk_length_s,omitempty"`
	StrideLengthS int32 `json:"stride_length_s,omitempty"`
	ForceFullSequences bool `json:"force_full_sequences,omitempty"`
	Language string `json:"language,omitempty"`
	Task string `json:"task,omitempty"`
	NumFrames int32 `json:"num_frames,omitempty"`
}
