/*
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TranslationRequestContract struct {
	Model string `json:"model"`
	Dtype string `json:"dtype"`
	Input string `json:"input"`
	SrcLang string `json:"srcLang"`
	TgtLang string `json:"tgtLang"`
}
