/*
 * Woolball AI Network API
 *
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TtsResponse struct {
	Audio string `json:"audio,omitempty"`
	Format string `json:"format,omitempty"`
	SampleRate int32 `json:"sample_rate,omitempty"`
}
